name: Deployment to Firebase
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build --prod --no-progress
      - name: Deploy
        run: yarn deploy -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
